version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: '⬆️ action'
    labels:
      - 'github-action :robot:'

  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: '⬆️ tf'
      include: 'scope'
    labels:
      - 'dependency :robot:'
