name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

permissions:
  contents: read
  packages: read

jobs:
  test:
    uses: stoe/policies/.github/workflows/policy-node-test.yml@main
