name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version:
          - 16
          - 18

    concurrency:
      group: test-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/dependency-review-action@0ff3da6f81b812d4ec3cf37a04e2308c7a723730
        if: github.event_name == 'pull_request'

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'
          cache: 'npm'

      - run: |
          npm pkg delete scripts.prepare
          npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npm run test --if-present

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - run: echo "success"
